# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: set env
        run: echo a=b | tee -a ${GITHUB_ENV}

      - name: get env
        run: cat ${GITHUB_ENV}

      # - name: Prepare Dockerfile
      #   run: |
      #     cat > Dockerfile << EOF
      #     FROM ubuntu:22.04
      #     RUN apt-get update && apt-get install -y systemd --no-install-recommends
      #     CMD [ "/lib/systemd/systemd" ]
      #     EOF
      #
      # - name: Build container image
      #   run: docker build -t cfengine -f ./Dockerfile .
      #
      #
      # - name: Run container
      #   run: docker run -d --privileged --name cfengine cfengine
      #
      # - name: check docker
      #   run: docker ps -a
      #
      # - name: check docker again
      #   run: sleep 2s && docker ps -a
      #
      # - name: run stuff in container
      #   run: docker exec -i cfengine echo hello
      #
