# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

defaults:
  run:
    shell: msys2 {0}
    working-directory: c:\w

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      - uses: msys2/setup-msys2@v2

      - name: Checkout Core
        uses: actions/checkout@v3
        with:
          repository: cfengine/core

      - name: Move core here
        run: mv "$GITHUB_WORKSPACE" /c/w
        working-directory: 'c:'

      # Runs a single command using the runners shell
      - name: whoami
        run: whoami

      - name: get CFEngine
        run: c:/msys64/usr/bin/wget.exe  http://buildcache.cfengine.com/packages/testing-pr/jenkins-master-nightly-pipeline-1263/PACKAGES_x86_64_mingw/cfengine-nova-3.22.0a-26402-x86_64.msi

      - name: install CFEngine
        run: msiexec /i cfengine-nova-3.22.0a-26402-x86_64.msi
        shell: pwsh

      - name: run cf-agent
        run: "'c:/Program Files/Cfengine/bin/cf-agent.exe' --version"

      - name: dummy cf-secret, idk
        run: "touch 'c:/Program Files/Cfengine/bin/cf-secret.exe' && chmod a+x 'c:/Program Files/Cfengine/bin/cf-secret.exe'"

      - name: run one test
        run: '"c:/Program Files/Cfengine/bin/cf-agent.exe" -D AUTO 013.cf -K'
        working-directory: "c:/w/tests/acceptance/00_basics/01_compiler"

      - name: run all tests
        run: 'USER=`whoami` OSTYPE=msys ./testall --bindir="c:/Program Files/Cfengine/bin"'
        working-directory: "c:/w/tests/acceptance"


      # - name: set env
      #   run: echo a=b | tee -a ${GITHUB_ENV}
      #
      # - name: get env
      #   run: cat ${GITHUB_ENV}

      # - name: Prepare Dockerfile
      #   run: |
      #     cat > Dockerfile << EOF
      #     FROM ubuntu:22.04
      #     RUN apt-get update && apt-get install -y systemd --no-install-recommends
      #     CMD [ "/lib/systemd/systemd" ]
      #     EOF
      #
      # - name: Build container image
      #   run: docker build -t cfengine -f ./Dockerfile .
      #
      #
      # - name: Run container
      #   run: docker run -d --privileged --name cfengine cfengine
      #
      # - name: check docker
      #   run: docker ps -a
      #
      # - name: check docker again
      #   run: sleep 2s && docker ps -a
      #
      # - name: run stuff in container
      #   run: docker exec -i cfengine echo hello
      #
