on: push

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "main job workflow_sha is [${{ github.workflow_sha }}]"

  call-workflow-1-in-local-repo:
    uses: Lex-2008/testrepo/.github/workflows/action.yml@ru

