name: CI

on:
  push:
  pull_request:

jobs:

  list-org-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Check available organization-hosted runners
        id: set-label
        env:
          # Using your new fine-grained PAT secret here
          GH_TOKEN: ${{ secrets.ORG_RUNNER_READER_TOKEN }}
        run: |
          sudo apt-get update && sudo apt-get install -y gron
          gh api orgs/reMarkable/actions/runners | gron


